export enum ColumnName {

    NAME = 'name',
    CODE_REPOSITORY = 'codeRepository',
    PROCESS_USING_MODEL = 'processUsingModel',
    INFORMATION = 'information',
    ALL_COLUMNS = 'all columns',
    TYPE = 'type',
    SOURCE = 'source',
    VALIDATED_BY = 'validatedBy',
    ID = 'id',
    LABEL= 'label',
    PROCESS = 'process',
    REPOSITORY = 'repository',
    MODEL_USING_PROCESS = 'modelUsingProcess',
    ACTION = 'action',
    ACCESS = 'access',
    SELECTED = 'selected',
    FAVORITE = 'isFavorite',
    CREATION_DATE = 'creationDate',
    MODIFICATION_DATE = 'modificationDate',
    GROUP = 'group',
    STATUS = 'executionStatus',
    REGENERATION_STATUS = 'regenerationStatus',
    DESCRIPTION = 'description',
    DEFAULT = 'default',
    CONFIDENTIAL = 'confidential',
    USERS = 'users',
    USERNAME = 'username',
    EDIT = 'edit',
    DELETE = 'delete',
    CREATION_STATUS = 'creation status'
}
