export enum ColumnName {

    NAME = 'Name',
    CODE_REPOSITORY = 'Code Repository',
    PROCESS_USING_MODEL = 'Process Using Model',
    INFORMATION = 'Information',
    ALL_COLUMNS = 'All columns',
    TYPE = 'Type',
    SOURCE = 'Source',
    VALIDATED_BY = 'Validated By',
    ID = 'Id',
    LABEL= 'Label',
    PROCESS = 'Process',
    REPOSITORY = 'Repository',
    MODEL_USING_PROCESS = 'Model Using Process',
    ACTION = 'Action',
    ACCESS = 'Access',
    SELECTED = 'Selected',
    FAVORITE = 'Favorite',
    CREATION_DATE = 'Creation Date',
    MODIFICATION_DATE = 'Modification Date',
    GROUP = 'Group',
    STATUS = 'Status',
    DESCRIPTION = 'Description',
    DEFAULT = 'Default',
    CONFIDENTIAL = 'Confidential',
    USERS = 'Users',
    USERNAME = 'Username',
    EDIT = 'Edit',
    DELETE = 'Delete'
}
