export enum Logo {
    ASSETS = '/assets/',
    SOS_TRADES_LOGO_WHITE = 'SOS_TRADES_LOGO_BLANC.svg',
    OSC_LOGO_WHITE = 'OscLogoWhite.png',
    GITHUB_LOGO_NAME ='GitHub_Logo.png',
    GITHUB_LOGO = 'github-mark.png',
    SOS_TRADES_LOGO_BLACK= 'SOS_TRADES_LOGO_NOIR.svg',
    GITHUB_FIRST_CONNECTION = 'github-first-connection.png'
}


export const LogoPath = {
    GITHUB_LOGO_NAME_PATH: Logo.ASSETS + Logo.GITHUB_LOGO_NAME,
    GITHUB_LOGO_PATH: Logo.ASSETS + Logo.GITHUB_LOGO,
    SOS_TRADES_LOGO_WHITE_PATH: Logo.ASSETS + Logo.SOS_TRADES_LOGO_WHITE,
    SOS_TRADES_LOGO_BLACK_PATH: Logo.ASSETS + Logo.SOS_TRADES_LOGO_BLACK,
    OSC_LOGO_WHITE_PATH: Logo.ASSETS +Logo.OSC_LOGO_WHITE,
    GITHUB_FIRST_CONNECTION_PATH: Logo.ASSETS + Logo.GITHUB_FIRST_CONNECTION

};